### ISSUE TITLE
Favicon wird bei Unterkategorien nicht angezeigt

### ISSUE THREAD

**Issue by Fanello** [danspringer/be_branding#19]
Die Anzeige des Favicon mit yrewrite funktioniert, jedoch nur in der ersten Navigations-Ebene:
https://advery.gartenbau-engesser.ch/
Sobald es tiefer geht wird das Favicon nicht angezeigt, da der Pfad nicht mehr stimmt:
https://advery.gartenbau-engesser.ch/gartenplanung/gartenarchitektur/

**Comment by danspringer** [comment]
Sollte mittlerweile behoben sein
