### ISSUE TITLE
LogIn-Logo über Backend index aufrufen

### ISSUE THREAD

**Issue by skerbis** [danspringer/be_branding#20]
Da das Frontend gesperrt sein könnte, sollte das Login-Logo nicht über die Frontend-Index ausgegeben werden. 
https://github.com/FriendsOfREDAXO/maintenance/issues/26

**Comment by helpy** [comment]
Fehler eingegrenzt: Er tritt nur auf, wenn als Logo ein SVG verwendet wird.
Siehe Code:
https://github.com/danspringer/be_branding/blob/82c70b32ca4ba599c950418010353793329c1af0/boot.php#L110

**Comment by skerbis** [comment]
Wird ein Medientyp nicht gefunden wird das Original ausgegeben. Ist soweit richtig.

**Comment by helpy** [comment]
Aber wäre das eine saubere Lösung?
Dann würde ich einen PullRequest einreichen ....

Oder gibt es einen anderen Weg, das SVG über die index.php ausgibt, ohne dieses Fallback zu nutzen?
Kann ich sicher davon ausgehen, dass der Fallback sich auch in Zukunft so verhält?

Ohne dem Argument rex_media_type geht es nicht (getestet).
Das heißt ich könnte einfach einen random-dummy-Medientyp erzeugen und verwenden.

**Comment by skerbis** [comment]
Ein anderer Weg fällt mir dazu aktuell nicht ein

**Comment by helpy** [comment]
Siehe Pull-Request:
==> https://github.com/danspringer/be_branding/pull/21

**Comment by danspringer** [comment]
Closed. Danke @helpy 
[https://github.com/danspringer/be_branding/pull/21](https://github.com/danspringer/be_branding/pull/21)
