### ISSUE TITLE
Favicon im Backend färben verhindert das Laden der Settings von Watson

### ISSUE THREAD

**Issue by f5alex** [danspringer/be_branding#28]
Mit aktivierter Option "Favicon im Backend färben" wird das Script zum Laden der Watson Settings (https://github.com/tbaddade/redaxo_watson) nicht in den Header geschrieben und Watson kann nicht aufgerufen werden.
Bei mir:
Redaxo 5.12.1
be_branding 1.5.1
watson 2.2.0

**Comment by tbaddade** [comment]
Die Notices müssten unterbunden werden, damit das HTML wieder valide ist.
