### ISSUE TITLE
mobile Navigation nicht sichtbar unter REX 5.13

### ISSUE THREAD

**Issue by f5alex** [danspringer/be_branding#29]
unter Redaxo 5.13.0 ist bei aktivem Addon be_branding die Mobile Navigation nicht sichtbar.
Navbar wir zwar "rausgefahren", die eigentliche Navigation hat aber ein "display:none".
Irgendwie stimmen die CSS-Klassen nicht mehr.
Entfernt man class="navbar-collapse collapse" funktioniert alles.

**Comment by oioix** [comment]
Kann ich bestätigen für Version 1.6.-beta2.
Wollte auch gerade ein issue anlegen. Sobald die Navi auf burger umschaltet fährt das dunkelgraue Hauptmenu zwar aus, ist aber komplett leer und das BE damit nicht bedienbar. Schaltet man das addon ab, ist alles wieder gut. 


![Screenshot 2021-12-15 | 09 02 46](https://user-images.githubusercontent.com/75900789/146149022-449b8101-cf7e-4398-91ea-cfe2d4d37d3b.jpg)


![Screenshot 2021-12-15 | 09 02 36](https://user-images.githubusercontent.com/75900789/146149028-d56402c5-dd5e-4fd4-ad7b-459dd4cc4502.jpg)
.

**Comment by danspringer** [comment]
Sollte mit der aktuellen Version behoben sein 
https://github.com/danspringer/be_branding/releases/tag/1.7

**Comment by oioix** [comment]
Top!
Danke!

**Comment by f5alex** [comment]
passt! Dankeschön!
