### ISSUE TITLE
Logo des Projekts wird bei Installation im Unterordner nicht angezeigt

### ISSUE THREAD

**Issue by aeberhard** [danspringer/be_branding#31]
in navigation.php sollte `rex_url::frontend()` vorangestellt werden

`                    echo '<img src="' . rex_url::frontend() . be_branding::checkExtension(rex_addon::get('be_branding')->getConfig('file')) . '" class="img-responsive center-block" style="padding: 20px 10px 5px 10px; width: 100%;"/></a>';`

**Comment by danspringer** [comment]
Im Login-Screen muss der Pfad auch noch angepasst werden:

https://github.com/danspringer/be_branding/blob/master/boot.php#L32

`  $ersetzen = array('<img src="' . be_branding::checkExtension($this->getConfig('file'. be_branding::getCurrentBeDomainId(true) )) . '" class="img-responsive center-block" style="padding: 10px 0px 15px 0px; width: 370px;"/></a><section class="rex-page-main-inner" id="rex-js-page-main">');`

**Comment by aeberhard** [comment]
Ja korrekt, hatte gar nicht gesehen dass da auch ein Logo ausgegeben wird.

**Comment by danspringer** [comment]
Fixed via https://github.com/danspringer/be_branding/commit/9f1e36bcf19e78d09a09324a94fddf9027b67cbc

**Comment by aeberhard** [comment]
In beta2 wird das Logo immer noch nicht angezeigt bei Installation im Unterordner.
Auch beim Loginscreen nicht.

**Comment by danspringer** [comment]
Was für ein Pfad wird da dann ausgegeben?

**Comment by aeberhard** [comment]
`<img src="http://localhost/media/logo.svg" ` wird ausgegeben

und mit Unterordner rex513 sollte es sein
`<img src="http://localhost/rex513/media/logo.svg" `

Sorry, wollte da einen Screenshot hochladen aber das klappt hier mit Firmenproxy nicht.

**Comment by danspringer** [comment]
Ah, okay. Danke.
Ich schaue mir das an. Habe es bisher immer nur mit Subdomains getestet, aber noch nicht mit Unterordner-Installationen

**Comment by aeberhard** [comment]
Ich arbeite immer lokal mit Unterordnern.

Gleiches Problem auch beim Logo im Login-Screen.

rex_url::frontend() liefert meine ich auch den Unterordner.

**Comment by danspringer** [comment]
Okay, dann muss ich mal schauen, ob `rex_url::frontend()` auch die richtige Domain liefert für eine Multidomaininstallation.
Theoretisch ist es eigtl. egal, da es ja nur darum geht, dass der Pfad zu einem existenten Bild stimmt. Aber schöne wäre es, wenn da auch die Domain stimmt.

**Comment by aeberhard** [comment]
Vielleicht ist bei Medien besser ohne den Host zu arbeiten.

Schau mal bei yrewrite
https://github.com/yakamara/redaxo_yrewrite/blob/9643e644bec340305ef3de64430c24794b280ee9/lib/yrewrite/yrewrite.php#L301-L309

**Comment by aeberhard** [comment]
Jetzt passt es Daniel :)

**Comment by danspringer** [comment]
Okay, cool. Dann kann ich das hier endlich schließen 😅
Ging ja lange genug.
Danke fürs Testen!
