### ISSUE TITLE
Notice: Trying to access array offset on value of type bool inredaxo\src\addons\be_branding\lib\be_branding.php on line 95

### ISSUE THREAD

**Issue by aeberhard** [danspringer/be_branding#33]
kommt beim Update über den Installer

**Comment by aeberhard** [comment]
und auch danach im Backend
php 7.4.10 und 8.1.10

keine Multidomainseite!

**Comment by danspringer** [comment]
Sollte mit https://github.com/danspringer/be_branding/commit/9f1e36bcf19e78d09a09324a94fddf9027b67cbc behoben sein.
